//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hazi.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hazi2Entities : DbContext
    {
        public hazi2Entities()
            : base("name=hazi2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Jogcim> Jogcims { get; set; }
        public virtual DbSet<IdoBejelentes> IdoBejelentes1 { get; set; }
        public virtual DbSet<FelhasznaloiProfilok> FelhasznaloiProfiloks { get; set; }
    }
}
