//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hazi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FelhasznaloiProfilok
    {
        public string UserName { get; set; }
        public System.DateTime SzuletesiDatum { get; set; }
        public string Vezeto { get; set; }
        public string ProfilKepUrl { get; set; }
    }
}
