//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hazi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdoBejelentes
    {
        public int ID { get; set; }
        public System.DateTime KezdetiDatum { get; set; }
        public System.DateTime VegeDatum { get; set; }
        public int JogcimID { get; set; }
        public string UserName { get; set; }
        public string LastEdit { get; set; }
        public string TorlesStatus { get; set; }
        public string UtolsoModosito { get; set; }
        public Nullable<System.DateTime> UtolsoModositas { get; set; }
        public string Statusz { get; set; }
    
        public virtual Jogcim Jogcim { get; set; }
    }
}
